# Generated by Django 5.2.7 on 2026-03-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_subscriptionplan_subscription_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
