# Generated by Django 5.2.7 on 2026-03-02 23:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_user_stripe_customer_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="is_paid",
            new_name="is_featured",
        ),
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
        migrations.AddField(
            model_name="post",
            name="allow_comments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("published", "Опубликован"),
                    ("archived", "В архиве"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="post",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="post",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PostMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="post_media/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Изображение"),
                            ("video", "Видео"),
                            ("audio", "Аудио"),
                            ("file", "Файл"),
                        ],
                        max_length=10,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="main.post",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PostVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(10)]
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, help_text="Краткое описание", max_length=500
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="posts/"),
                ),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("en", "Английский"),
                            ("kk", "Казахский"),
                        ],
                        default="ru",
                        max_length=2,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "change_summary",
                    models.CharField(
                        blank=True,
                        help_text="Краткое описание изменений",
                        max_length=200,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="main.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="main.postversion",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "status"], name="main_post_author__005844_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-published_at"], name="main_post_publish_897ff5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postversion",
            index=models.Index(
                fields=["post", "language"], name="main_postve_post_id_7937c4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postversion",
            unique_together={("post", "version_number")},
        ),
    ]
