# Generated by Django 5.2.7 on 2026-03-02 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_post_options_rename_is_paid_post_is_featured_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("free", "Бесплатный"),
                    ("paid_once", "Разовый платёж"),
                    ("subscription", "По подписке"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Цена для разового доступа",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="required_subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="Требуемый план подписки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="accessible_posts",
            field=models.ManyToManyField(
                blank=True, related_name="subscription_plans", to="main.post"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="user",
            name="total_purchases",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="PostPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(max_length=100, unique=True),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="main.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "post")},
            },
        ),
        migrations.AddField(
            model_name="post",
            name="purchased_by",
            field=models.ManyToManyField(
                related_name="purchased_posts",
                through="main.PostPurchase",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
