# Generated by Django 5.2.7 on 2026-03-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_add_user_balance_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["access_type"], name="main_post_access__161413_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["status"], name="main_post_status_7e661c_idx"),
        ),
    ]
